title: Financial Feeling
baseurl: ""
url: "https://financialfeeling.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude files from processing
exclude:
  - node_modules
  - .git
  - .github
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - tsconfig.json
  - next.config.mjs
  - postcss.config.mjs
  - tailwind.config.ts
  - deploy.sh
  - setup-pages.sh
  - check-status.sh
  - fix-jekyll-issue.sh
  - README.md
  - .env.local
  - .env.example
  - .gitignore
  - .eslintrc.json
  - components.json
  - lib
  - hooks
  - actions
  - middleware.ts
  - supabase_migrations
  - animated-gradient
  - my-app
  - my-app-v0
  - my-app-native
  - my-app-combined
  - app
  - components
  - public
  - styles
  - out

# Include all files in root (Next.js static export)
include:
  - _next
  - chunks
  - css
  - media
  - fonts
  - dashboard
  - login
  - signup
  - stock-analysis
  - example-page
  - 404
  - 404.html
  - index.html
  - favicon.ico
  - favicon.svg
  - apple-touch-icon.png
  - placeholder-logo.png
  - placeholder-logo.svg
  - placeholder-user.jpg
  - placeholder.jpg
  - placeholder.svg

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme
theme: jekyll-theme-primer

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Jekyll processing settings
keep_files:
  - _next
  - chunks
  - css
  - media
  - fonts
  - dashboard
  - login
  - signup
  - stock-analysis
  - example-page
  - 404
  - 404.html
  - index.html
  - favicon.ico
  - favicon.svg
  - apple-touch-icon.png
  - placeholder-logo.png
  - placeholder-logo.svg
  - placeholder-user.jpg
  - placeholder.jpg
  - placeholder.svg 